// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aPIKeyByToken = `-- name: APIKeyByToken :one
SELECT
    id, organisation_id, name, token
FROM organisation_api_keys oak
WHERE oak.token=$1
`

func (q *Queries) APIKeyByToken(ctx context.Context, token string) (OrganisationApiKey, error) {
	row := q.db.QueryRow(ctx, aPIKeyByToken, token)
	var i OrganisationApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Token,
	)
	return i, err
}

const getOrganisationByID = `-- name: GetOrganisationByID :one
SELECT 
    id, name
FROM 
    organisations o
WHERE o.id=$1
`

func (q *Queries) GetOrganisationByID(ctx context.Context, id pgtype.UUID) (Organisation, error) {
	row := q.db.QueryRow(ctx, getOrganisationByID, id)
	var i Organisation
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getOrganisationMembers = `-- name: GetOrganisationMembers :many
SELECT organisation_id, member_id, role FROM organisation_members WHERE organisation_id = $1
`

func (q *Queries) GetOrganisationMembers(ctx context.Context, organisationID pgtype.UUID) ([]OrganisationMember, error) {
	rows, err := q.db.Query(ctx, getOrganisationMembers, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganisationMember
	for rows.Next() {
		var i OrganisationMember
		if err := rows.Scan(&i.OrganisationID, &i.MemberID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganisationsForMember = `-- name: GetOrganisationsForMember :many
SELECT
    o.id, o.name
FROM organisations o 
INNER JOIN organisation_members om
    ON o.id=om.organisation_id
WHERE om.member_id = $1
`

func (q *Queries) GetOrganisationsForMember(ctx context.Context, memberID pgtype.UUID) ([]Organisation, error) {
	rows, err := q.db.Query(ctx, getOrganisationsForMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organisation
	for rows.Next() {
		var i Organisation
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAPIKey = `-- name: UpsertAPIKey :exec
INSERT INTO organisation_api_keys (id, organisation_id, name, token)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id)
DO UPDATE
SET name = EXCLUDED.name
`

type UpsertAPIKeyParams struct {
	ID             pgtype.UUID
	OrganisationID pgtype.UUID
	Name           string
	Token          string
}

// name is the only property that may be updated after creation
func (q *Queries) UpsertAPIKey(ctx context.Context, arg UpsertAPIKeyParams) error {
	_, err := q.db.Exec(ctx, upsertAPIKey,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.Token,
	)
	return err
}

const upsertOrganisation = `-- name: UpsertOrganisation :exec
INSERT INTO organisations (id, name)
VALUES ($1, $2)
ON CONFLICT (id)
DO UPDATE
SET name = EXCLUDED.name
`

type UpsertOrganisationParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpsertOrganisation(ctx context.Context, arg UpsertOrganisationParams) error {
	_, err := q.db.Exec(ctx, upsertOrganisation, arg.ID, arg.Name)
	return err
}

const upsertOrganisationMember = `-- name: UpsertOrganisationMember :exec
INSERT INTO organisation_members (organisation_id, member_id, "role")
VALUES ($1, $2, $3)
ON CONFLICT (organisation_id, member_id)
DO UPDATE
SET "role" = EXCLUDED.role
`

type UpsertOrganisationMemberParams struct {
	OrganisationID pgtype.UUID
	MemberID       pgtype.UUID
	Role           string
}

func (q *Queries) UpsertOrganisationMember(ctx context.Context, arg UpsertOrganisationMemberParams) error {
	_, err := q.db.Exec(ctx, upsertOrganisationMember, arg.OrganisationID, arg.MemberID, arg.Role)
	return err
}
