// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GithubUser struct {
	UserID pgtype.UUID
	// The node ID of this user from github, so we can map them back when necessary.
	// Mostly necessary during the login process.
	NodeID string
}

type User struct {
	// Primary key and unique ID for a user in the system.
	ID pgtype.UUID
	// Email address for the given user, used primarily for contacting them.
	Email string
	// Preferred name to display when referencing this user, free text could be a real name, partial name, nickname etc.
	Name string
}
