// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const delete = `-- name: Delete :exec
DELETE FROM refresh_tokens
WHERE id=$1
`

func (q *Queries) Delete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const getRefreshTokenByValue = `-- name: GetRefreshTokenByValue :one
SELECT
    id, user_id, value, issued_at, expires_at
FROM refresh_tokens
WHERE value=$1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByValue(ctx context.Context, value string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByValue, value)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Value,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (id, value, issued_at, expires_at, user_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRefreshTokenParams struct {
	ID        pgtype.UUID
	Value     string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UserID    pgtype.UUID
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.Value,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.UserID,
	)
	return err
}
