// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByGithubUserNodeID = `-- name: GetUserByGithubUserNodeID :one
SELECT 
    id, email, name, user_id, node_id
FROM 
    users u
INNER JOIN github_users ghu
    ON u.id=ghu.user_id
WHERE ghu.node_id=$1
`

type GetUserByGithubUserNodeIDRow struct {
	ID     pgtype.UUID
	Email  string
	Name   string
	UserID pgtype.UUID
	NodeID string
}

func (q *Queries) GetUserByGithubUserNodeID(ctx context.Context, nodeID string) (GetUserByGithubUserNodeIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByGithubUserNodeID, nodeID)
	var i GetUserByGithubUserNodeIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.NodeID,
	)
	return i, err
}
