// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByGithubUserNodeID = `-- name: GetUserByGithubUserNodeID :one
SELECT 
    id, email, name, user_id, node_id
FROM 
    users u
INNER JOIN github_users ghu
    ON u.id=ghu.user_id
WHERE ghu.node_id=$1
`

type GetUserByGithubUserNodeIDRow struct {
	ID     pgtype.UUID
	Email  string
	Name   string
	UserID pgtype.UUID
	NodeID string
}

func (q *Queries) GetUserByGithubUserNodeID(ctx context.Context, nodeID string) (GetUserByGithubUserNodeIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByGithubUserNodeID, nodeID)
	var i GetUserByGithubUserNodeIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.NodeID,
	)
	return i, err
}

const getUserID = `-- name: GetUserID :one
SELECT 
    id, email, name, user_id, node_id
FROM 
    users u
INNER JOIN github_users ghu
    ON u.id=ghu.user_id
WHERE u.id=$1
`

type GetUserIDRow struct {
	ID     pgtype.UUID
	Email  string
	Name   string
	UserID pgtype.UUID
	NodeID string
}

func (q *Queries) GetUserID(ctx context.Context, id pgtype.UUID) (GetUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserID, id)
	var i GetUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.NodeID,
	)
	return i, err
}

const upsertGithubUser = `-- name: UpsertGithubUser :exec
INSERT INTO github_users (user_id, node_id)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE
SET node_id = EXCLUDED.node_id
`

type UpsertGithubUserParams struct {
	UserID pgtype.UUID
	NodeID string
}

func (q *Queries) UpsertGithubUser(ctx context.Context, arg UpsertGithubUserParams) error {
	_, err := q.db.Exec(ctx, upsertGithubUser, arg.UserID, arg.NodeID)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, email, name)
VALUES ($1, $2, $3)
ON CONFLICT (id)
DO UPDATE
SET email = EXCLUDED.email,
    name = EXCLUDED.name
`

type UpsertUserParams struct {
	ID    pgtype.UUID
	Email string
	Name  string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser, arg.ID, arg.Email, arg.Name)
	return err
}
