services:
  app:
    image: hashicorp/http-echo:latest
    command:
      - -text="api"
    labels:
      - "traefik.http.routers.api.rule=Host(`${API_HOST}`)"
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.api.loadbalancer.server.port=5678"
      - "traefik.http.routers.api.tls=true"

  mkdocs:
    build:
      context: .
      dockerfile: ./etc/mkdocs/Dockerfile
    volumes:
      - .:/docs
    labels:
      - "traefik.http.routers.api-mkdocs.rule=Host(`${DOCS_HOST}`)"
      - "traefik.enable=true"
      - "traefik.http.routers.api-mkdocs.entrypoints=websecure"
      - "traefik.http.services.api-mkdocs.loadbalancer.server.port=8000"
      - "traefik.http.routers.api-mkdocs.tls=true"