services:
  app:
    build:
      context: .
      target: dev
    environment:
      AIR_DEBUG: ${AIR_DEBUG:-false}
      # See: https://github.com/testcontainers/testcontainers-go/issues/2477#issuecomment-2417815745
      TESTCONTAINERS_RYUK_DISABLED: true
      # See .local/docker/watch.sh
      # This is the subcommand of the binary we wanna run
      APP_CMD: serve
    working_dir: /app
    volumes:
      - ".:/app"
      # So we can use testcontainers
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
        - "traefik.http.routers.api.rule=Host(`${API_HOST}`)"
        - "traefik.enable=true"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.services.api.loadbalancer.server.port=1323"
        - "traefik.http.routers.api.tls=true"

  mkdocs:
    build:
      context: .
      dockerfile: ./etc/mkdocs/Dockerfile
    volumes:
      - .:/docs
    labels:
      - "traefik.http.routers.api-mkdocs.rule=Host(`${DOCS_HOST}`)"
      - "traefik.enable=true"
      - "traefik.http.routers.api-mkdocs.entrypoints=websecure"
      - "traefik.http.services.api-mkdocs.loadbalancer.server.port=8000"
      - "traefik.http.routers.api-mkdocs.tls=true"